#!/usr/bin/env php
<?php
require(dirname(__FILE__) . '/../webroot.conf.php');

function build($directory) {
	$meta_file = $directory . DS . 'meta.json';
	$page_files = glob($directory . DS . '[0-9][0-9].textile');

	// Sanity checks:
	if (!is_dir($directory)) {
		error('Directory `' . $directory . '\' does not exist');
	}
	if (!file_exists($meta_file)) {
		error('Required file `' . $meta_file . '\' not found');
	}
	if ($page_files == false) {
		error('No Textile files found');
	}

	// Build the article
	$json = file_get_contents($meta_file);
	$article = new Article($json);
	$article->generatePath($directory);
	foreach ($page_files as $file) {
		$article->addPage($file);
	}
	$article->title = get_title($page_files[0]);
	$article->update();

	ArticleMap::addArticle($article);
}

function error($msg) {
	printf('ERROR: %s%s', $msg, PHP_EOL);
	exit(1);
}

function get_title($file) {
	$fh = fopen($file, 'r');
	while (!FString::startsWith($line = fgets($fh), 'h1.'));
	$title = trim(str_replace('h1.', '', $line));
	return $title;
}

function main() {
	global $argc, $argv;
	if ($argc < 2) {
		printf("USAGE: %s article_dir%s", $argv[0], PHP_EOL);
	}
	build($argv[1]);
}

main();
