#!/usr/bin/env php
<?php
// TODO: allow for an arg describing where to output the array to. Could be the
// first arg or the last one (like cp)
function get_map($filename) {
	require($filename);
	return array(
		'dir' => $data['dir'],
		'url' => $data['url'],
		'published' => strtotime($data['published']),
		'tags' => $data['tags']
	);
}

if ($argc == 1) {
	echo "Nothing to process data for!\n";
	exit(1);
}

$date_map = array();
$url_map  = array();
foreach (array_slice($argv, 1) as $file) {
	$m = get_map($file);
	$date_map[$m['published']] = $m;
	$url_map[$m['url']] = $m;
}
// Save a ton of time later by just ordering the keys now.
krsort($date_map, SORT_NUMERIC);

ob_start();
echo "<?php\n";
echo '$_date_map = ';
var_export($date_map);
echo ";\n";
echo '$_url_map = ';
var_export($url_map);
echo ";\n";
