#!/usr/bin/env php
<?php
// TODO: allow for an arg describing where to output the array to. Could be the
// first arg or the last one (like cp)
function get_map($filename) {
	require($filename);
	return array(
		'basename' => basename(dirname($filename)),
		'published' => strtotime($data['published']),
		'tags' => $data['tags']
	);
}

if ($argc == 1) {
	echo "Nothing to process data for!\n";
	exit(1);
}

$map = array();
foreach (array_slice($argv, 1) as $file) {
	$m = get_map($file);
	$map[$m['published']] = $m;
}
// Save a ton of time later by just ordering the keys now.
krsort($map, SORT_NUMERIC);

ob_start();
echo "<?php\n";
echo '$map = ';
var_export($map);
echo ";\n";
