#!/usr/bin/env php
<?php

function get_date($filename) {
	$fh = fopen($filename, 'r');
	$date = null;
	while ($line = fgets($fh)) {
		if (strpos($line, 'published') !== false) {
			list( , $date, ) = explode("'", $line);
		}
	}
	fclose($fh);
	return $date;
}

if ($argc == 1) {
	echo "Nothing to process dates for!\n";
	exit(1);
}

$map = array();
foreach (array_slice($argv, 1) as $file) {
	$date = get_date($file);
	if ($date == null) {
		echo "No date found in {$file}\n";
		exit(2);
	}
	$map[strtotime($date)] = basename(dirname($file));
}

ob_start();
echo "<?php\n";
echo '$map = ';
var_export($map);
