#!/usr/bin/python
import json
import os.path
import sys
import uuid

def add_uuid(filename):
	if os.path.exists(filename) == False:
		print 'File does not exist:', filename
		exit(2)
	file = open(filename)
	meta = json.load(file)
	if not 'pubDate' in meta:
		print '`pubDate\' not defined in meta information'
		exit(3)
	
	file.close()

def get_uuid(json):
	return uuid.uuid5(uuid.NAMESPACE_URL, 'keyboardfu.com')

def main():
	if len(sys.argv) != 2:
		print 'Usage:', sys.argv[0], '<filename>'
		exit(1)
	add_uuid(sys.argv[1])

if __name__ == '__main__':
	main()
