#!/usr/bin/python
import json
import os.path
import sys
import time
import uuid

def add_uuid(filename):
	if os.path.isdir(filename):
		filename = os.path.join(filename, 'meta.json')
	if not os.path.exists(filename):
		print 'File does not exist:', filename
		exit(2)
	file = open(filename, 'r')
	meta = json.load(file)
	file.close()

	if not 'pubDate' in meta:
		print '`pubDate\' not defined in meta information'
		exit(3)
	path = os.path.basename(os.path.dirname(filename))
	date = time.strptime(meta['pubDate'], '%a %b %d %H:%M:%S %Z %Y')
	meta['uuid'] = get_uuid(date, path)

	file = open(filename, 'w')
	file.write(json.dumps(meta, indent=8, separators=(',', ': ')).replace(' '*8, '\t'))
	file.write('\n')
	file.close()

def get_uuid(date, path):
	url = 'http://keyboardfu.com/%s/%s'%(time.strftime('%Y/%m/%d', date), path)
	return str(uuid.uuid5(uuid.NAMESPACE_URL, url))

def main():
	if len(sys.argv) != 2:
		print 'Usage:', sys.argv[0], '<filename>'
		exit(1)
	add_uuid(sys.argv[1])

if __name__ == '__main__':
	main()
